project_id = "omaadiydsjiacokhwgjf"

[functions.seed-data]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.audit-auth-hook]
verify_jwt = false

[functions.vault-crypto]
verify_jwt = false

[functions.master-admin]
verify_jwt = false

[functions.generate-canvas-flow]
verify_jwt = false

[functions.send-email-notification]
verify_jwt = false

[functions.self-service-signup]
verify_jwt = false
